### ISSUE TITLE
Nice code

### ISSUE THREAD

**Issue by LaurentBerger** [sturkmen72/HOG-object-detection#1]
Some small problem in int test_trained_detector( String obj_det_filename, String test_dir, String videofilename )
instead of  https://github.com/sturkmen72/HOG-object-detection/blob/master/train_HOG.cpp#L328-L334 I think this

```
        if (cap.isOpened())
            cap >> img;
		else
                {
                    if(i < files.size()-1)
                    img = imread(files[i]);
                }

```

https://github.com/sturkmen72/HOG-object-detection/blob/master/train_HOG.cpp#L368 path to positive or train images

**Comment by sturkmen72** [comment]
Thank you @LaurentBerger i will be happy if you make this kind of advices on the actual [PR](https://github.com/opencv/opencv/pull/9541) i think by this way you also help core developers when reviewing

**Comment by sturkmen72** [comment]
@LaurentBerger please see https://github.com/sturkmen72/HOG-object-detection/commit/f2849f5e9c868249c1b2abdd3d2d7bcefbdbebc8
